import { useEffect } from "react";
import { useAuthStore } from "../store";

// ⚠️ REPLACE THIS WITH YOUR ACTUAL PUBLIC KEY 
// Generate using: ssh-keygen -t rsa -b 2048 -m PEM -f jwtRS256.key
// Use the .pub file contents here.
export const PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzwE7...
-----END PUBLIC KEY-----`;

/**
 * Native Web Crypto API RS256 JWT Verifier
 * No external dependencies required.
 */
export async function verifyRS256Token(token: string): Promise<any | null> {
  try {
    const parts = token.split('.');
    if (parts.length !== 3) return null;

    const [headerB64, payloadB64, signatureB64] = parts;
    const textEncoder = new TextEncoder();
    const data = textEncoder.encode(`${headerB64}.${payloadB64}`);
    
    // Decode base64url signature
    const signature = Uint8Array.from(atob(signatureB64.replace(/-/g, '+').replace(/_/g, '/')), c => c.charCodeAt(0));
    
    // Clean and decode the PEM string
    const pemContents = PUBLIC_KEY.replace(/-----BEGIN PUBLIC KEY-----/g, '')
                                  .replace(/-----END PUBLIC KEY-----/g, '')
                                  .replace(/\s/g, '');
    
    const binaryDerString = atob(pemContents);
    const binaryDer = new Uint8Array(binaryDerString.length);
    for (let i = 0; i < binaryDerString.length; i++) {
      binaryDer[i] = binaryDerString.charCodeAt(i);
    }

    // Import the public key
    const publicKey = await crypto.subtle.importKey(
      "spki",
      binaryDer.buffer,
      { name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" },
      true,
      ["verify"]
    );

    // Verify the signature against the data
    const isValid = await crypto.subtle.verify(
      "RSASSA-PKCS1-v1_5",
      publicKey,
      signature,
      data
    );

    if (isValid) {
      // Decode and return payload
      return JSON.parse(atob(payloadB64.replace(/-/g, '+').replace(/_/g, '/')));
    }
    return null;
  } catch (e) {
    console.error("JWT Verification failed. Token might be tampered with.");
    return null;
  }
}

/**
 * React Hook to be placed in your root <App /> component.
 * It quietly verifies the token in the background on load.
 */
export function usePremiumValidation() {
  const { premiumToken, setPremiumVerified } = useAuthStore();

  useEffect(() => {
    async function validate() {
      if (!premiumToken) {
        setPremiumVerified(false);
        return;
      }
      const payload = await verifyRS256Token(premiumToken);
      
      // If payload exists, signature is mathematically proven to be generated by your Edge Function
      setPremiumVerified(!!payload);
    }
    
    validate();
  }, [premiumToken, setPremiumVerified]);
}